"""empty message

Revision ID: a6bcda216273
Revises: 
Create Date: 2025-07-02 17:40:00.112349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6bcda216273'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('apellido', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('altura', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('peso_actual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('meta_peso', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('meta_peso')
        batch_op.drop_column('peso_actual')
        batch_op.drop_column('altura')
        batch_op.drop_column('fecha_nacimiento')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
